version: 2
jobs:
  deployable_check:
    docker:
      - image: eklhad/terrasnek-circleci:0.1
    working_directory: ~/terrasnek
    steps:
      - checkout
      - run:
          name: check the code meets deployable standards
          command: |
            make lint
            make contributor_check
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - deployable_check